// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGQeBJYrnUN8T0LYKKmif_C8uEZKgaD8',
    appId: '1:769990493632:web:daa3ddb3f2bdfd3a27b425',
    messagingSenderId: '769990493632',
    projectId: 'trainer-app-25b10',
    authDomain: 'trainer-app-25b10.firebaseapp.com',
    storageBucket: 'trainer-app-25b10.appspot.com',
    measurementId: 'G-PJRS0J8S4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu8DXytZKUoccIGCXGtC-pENS3QpwqJWU',
    appId: '1:769990493632:android:a368b1aba14b208927b425',
    messagingSenderId: '769990493632',
    projectId: 'trainer-app-25b10',
    storageBucket: 'trainer-app-25b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoyCAFtdExKQAR2CCOJzKQaapE1OkqrTk',
    appId: '1:769990493632:ios:0997e62d595b177927b425',
    messagingSenderId: '769990493632',
    projectId: 'trainer-app-25b10',
    storageBucket: 'trainer-app-25b10.appspot.com',
    iosBundleId: 'com.example.trainerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoyCAFtdExKQAR2CCOJzKQaapE1OkqrTk',
    appId: '1:769990493632:ios:abc29d26254583ab27b425',
    messagingSenderId: '769990493632',
    projectId: 'trainer-app-25b10',
    storageBucket: 'trainer-app-25b10.appspot.com',
    iosBundleId: 'com.example.trainerApp.RunnerTests',
  );
}
